name: Docker check
on: [workflow_dispatch]
env: 
  ECR_URI: ${{secrets.ECR_URI}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t web-app:${{ github.sha }} ./web-app/
      - name: Check if docker image was built 
        run: docker images
      - name:  Tag docker image for AWS ECR
        run: docker tag web-app:${{ github.sha }} $ECR_URI:${{ github.sha }}
      - name: Check if docker tags was changed 
        run: docker images