name: Docker check
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t webapi:$(date +"%F_%H%M%S") ./web-app/
      - name: Check if docker image was built 
        run: docker images