name: Deploy to AWS ECR
on: [workflow_dispatch]
env: 
  ECR_URI: ${{secrets.ECR_URI}}
  AWS_REGION: eu-central-1
  ECR_REPOSITORY: repository/webapp-repository
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v6.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build docker image
        run: docker build -t web-app:${{ github.sha }} ./web-app/

      - name: Tag docker image and push it to AWS ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha  }}
        run: |
          docker tag web-app:$IMAGE_TAG $ECR_REGISTRY/ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT